version: '3'
services:
  train:
    image: container_test_sagemaker_py38_cpu
    volumes:
      - ../data:/opt/ml/input/data
      - ../config:/opt/ml/input/config
      - ../model:/opt/ml/model
      - ../output:/opt/ml/output
    command: train
    entrypoint: ["src/container/executor.sh"]
  deploy:
    image: container_test_sagemaker_py38_cpu
    volumes:
      - ../model:/opt/ml/model
    command: serve
    entrypoint: ["src/container/executor.sh"]
    ports:
      - "8080:8080"
