name: CI Linting

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'images/*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run linting
        run: |
          make lint
